<!-- end of contents -->
</div>

<div id="themeFooter">
	<p>
		<a href="<?=$wikiPath?>/<?=$PAGE?>?edit">Edit this page</a> |
		<a href="<?=$wikiPath?>/<?=$PAGE?>?info">Information for this page</a> |
		...
	</p>
</div>

<div id="themeCopyright">
	<p>
		<a href="http://validator.w3.org/check/referer">
			<img src="<?=$wikiRoot?>/<?=$wikiTheme?>/valid_xhtml11.png" alt="This page is valid XHTML 1.1 document." height="31" width="88" class="valid" />
		</a>
		<a href="http://jigsaw.w3.org/css-validator/check/referer">
			<img src="<?=$wikiRoot?>/<?=$wikiTheme?>/valid_css2.png" alt="This page is valid CSS 2." height="31" width="88" class="valid" />
		</a>
		This page is generated by <b><a href="http://dev.tokigun.net/tiniwiki/">TiniWiki</a> version <?=$wikiVersion?></b>.<br />
		Elasped Time: <?=sprintf("%.6f", _elaspedtime())?> seconds.
	</p>
</div>

</body>
</html>

