<!-- end of contents -->
</div>

<div id="themeFooter">
	<p><a href="http://validator.w3.org/check/referer">XHTML 1.1</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS 2</a> | Generated by TiniWiki. <?=sprintf("%.6f",_elaspedtime())?></p>
</div>

</td></tr></table>
</body>
</html>

